server:
 port: 7001

spring:
 application:
  name: eureka-1
 security:
  user:
   name: y51288033
   password: wasd123..wasd
eureka:
 instance:
  hostname: Eureka-1 # eureka服务端实例名称
 client:
  #false表示不向注册中心注册自己
  register-with-eureka: false
  #false表示自己就是注册中心
  fetch-registry: false
  service-url:
   # 设置与 eureka server交互的地址
   defaultZone: http://y51288033:wasd123..wasd@127.0.0.1:7001/eureka/